version: '3.8'

services:
  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    links:
      - "server:sv"
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - './server:/app'
      - '/node_modules'
    ports:
      - '3000:3000'
